name: Release

on:
  push:
    tags:
      - '*'
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: dotnet build -c Release
      
    - name: Publish win x64
      run: |
        dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained false -o release/win-x64
        dotnet publish -r win-x86 -c Release /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained false -o release/win-x86
        dotnet publish -r linux-x64 -c Release /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained false -o release/linux-x64
        dotnet publish -r linux-arm -c Release /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained false -o release/linux-arm
        dotnet publish -r osx-x64 -c Release /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained false -o release/osx-x64
      
    - uses: ncipollo/release-action@v1
      with:
        name: Release ${{ github.ref }}
        artifacts: "release.tar.gz,foo/*.txt"
        bodyFile: "body.md"
