name: Release

on:
  push:
    tags:
      - '*'
    
jobs:
  release:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build and publish to folder 
      shell: pwsh
      run: ./publish.ps1

    - name: Get the version
      id: version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: Release ${{ steps.version.outputs.VERSION }}
        artifacts: "release/*"
